enum new_DIV_eModifiers
{
    MDF_DIV_PROPITAL = 60,
    MDF_DIV_GOLDSTAR,
    MDF_DIV_OBDOLBOS,
	MDF_DIV_COMBAT_STIMULATOR_SJ1,
	MDF_DIV_COMBAT_STIMULATOR_SJ6,
	MDF_DIV_COMBAT_STIMULATOR_ZAGUSTIN,
	MDF_DIV_COMBAT_STIMULATOR_ETG,
	MDF_DIV_COMBAT_STIMULATOR_MULE,
    MDF_DIV_OBDOLBOS2,
    MDF_DIV_PERFOTOR,
    MDF_DIV_XTG12,
    MDF_HEALING_AFAK,
    MDF_HEALING_AI2,
    MDF_HEALING_GRIZLY,
    MDF_HEALING_IFAK,
    MDF_HEALING_SALEWA,
    COUNT
};
